create table public.assignment (
  id bigint generated by default as identity not null,
  assigned_at timestamp with time zone not null default now(),
  prison_id bigint not null,
  cell_id bigint not null,
  inmate_id bigint not null,
  officer_id bigint not null,
  status character varying(20) not null default 'active'::character varying,
  ended_at timestamp with time zone null,
  reason character varying(50) null,
  constraint Assignment_pkey primary key (id),
  constraint Assignment_inmateId_fkey foreign KEY (inmate_id) references inmate (id),
  constraint Assignment_officerId_fkey foreign KEY (officer_id) references officer (id),
  constraint Assignment_cellId_fkey foreign KEY (cell_id) references cell (id),
  constraint Assignment_prisonId_fkey foreign KEY (prison_id) references prison (id),
  constraint assignment_ended_check check (
    (
      (
        ((status)::text = 'active'::text)
        and (ended_at is null)
      )
      or (
        ((status)::text <> 'active'::text)
        and (ended_at is not null)
      )
    )
  ),
  constraint assignment_status_check check (
    (
      (status)::text = any (
        (
          array[
            'active'::character varying,
            'transferred'::character varying,
            'released'::character varying,
            'deceased'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create unique INDEX IF not exists idx_assignment_unique_active on public.assignment using btree (inmate_id) TABLESPACE pg_default
where
  ((status)::text = 'active'::text);

create table public.cell (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  capacity smallint null default '0'::smallint,
  prison_id bigint not null,
  constraint Cell_pkey primary key (id),
  constraint Cell_prisonId_fkey foreign KEY (prison_id) references prison (id)
) TABLESPACE pg_default;

create table public.inmate (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  first_name text null,
  last_name text null,
  is_violent boolean null,
  is_juvenile boolean null,
  constraint Inmate_pkey primary key (id)
) TABLESPACE pg_default;

create table public.officer (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  first_name text null,
  last_name text null,
  prison_id bigint not null,
  constraint Officer_pkey primary key (id),
  constraint Officer_prisonId_fkey foreign KEY (prison_id) references prison (id)
) TABLESPACE pg_default;

create table public.prison (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  constraint Prison_pkey primary key (id)
) TABLESPACE pg_default;